strcpy(company[0].name, "TC Energy");
strcpy(company[1].name, "Canadian Utilities");
strcpy(company[2].name, "Bank of Nova Scotia");
strcpy(company[3].name, "TransAlta Renewables");
strcpy(company[4].name, "Toronto Dominion Bank");
strcpy(company[0].name, "TRP.TO");
strcpy(company[1].name, "CU.TO");
strcpy(company[2].name, "BNS.TO");
strcpy(company[3].name, "RNW.TO");
strcpy(company[4].name, "TD.TO");
company[0].div = 56;
company[1].div = 1.76;
company[2].div = 3.6;
company[3].div = 0.94;
company[4].div = 3.16;
company[0].stockPrice = 55;
company[1].stockPrice = 31.7;
company[2].stockPrice = 70.08;
company[3].stockPrice = 21.75;
company[4].stockPrice = 74.81;